### ISSUE TITLE
SECURITY - please update to node 6.11.1 version

### ISSUE THREAD

**Issue by popod** [johnmuhl/electron-crash-report-server#21]
Please update package.json "engine" node version to 6.11.1 du to this security break: https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/.

**Comment by johnmuhl** [comment]
Thanks for the heads up.

**Comment by johnmuhl** [comment]
@popod did you try installing on Heroku with the old value (`^6.10.3`) and not get `6.11.1`? 

I'm curious because https://semver.npmjs.com/ indicates that a new install with `"node": "^6.10.3"` should get the whatever the latest `6.x` version is (e.g. `6.11.1`). If Heroku is not respecting semver then I can open an issue with them or relax the version to something like `8.x`.

**Comment by popod** [comment]
Thanks for the "fix". I've try to stop/start my Heroku node, but I've not redeploy it.
